package com.rodrigoaads.mytime.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006D3A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF25E683)
val onPrimaryContainerLight = Color(0xFF004220)
val secondaryLight = Color(0xFF256B40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFAEF7C0)
val onSecondaryContainerLight = Color(0xFF07562D)
val tertiaryLight = Color(0xFF006496)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF95CEFF)
val onTertiaryContainerLight = Color(0xFF003B5B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF2FCF0)
val onBackgroundLight = Color(0xFF151E17)
val surfaceLight = Color(0xFFF2FCF0)
val onSurfaceLight = Color(0xFF151E17)
val surfaceVariantLight = Color(0xFFD6E7D6)
val onSurfaceVariantLight = Color(0xFF3C4A3E)
val outlineLight = Color(0xFF6B7B6D)
val outlineVariantLight = Color(0xFFBACBBB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2A332B)
val inverseOnSurfaceLight = Color(0xFFEAF3E8)
val inversePrimaryLight = Color(0xFF1EE381)

val primaryDark = Color(0xFF68FFA2)
val onPrimaryDark = Color(0xFF00391B)
val primaryContainerDark = Color(0xFF00D577)
val onPrimaryContainerDark = Color(0xFF003519)
val secondaryDark = Color(0xFF8FD6A2)
val onSecondaryDark = Color(0xFF00391B)
val secondaryContainerDark = Color(0xFF004A25)
val onSecondaryContainerDark = Color(0xFF9CE4AF)
val tertiaryDark = Color(0xFFCFE7FF)
val onTertiaryDark = Color(0xFF003350)
val tertiaryContainerDark = Color(0xFF7CC1F9)
val onTertiaryContainerDark = Color(0xFF00304C)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0D150F)
val onBackgroundDark = Color(0xFFDBE5DA)
val surfaceDark = Color(0xFF0D150F)
val onSurfaceDark = Color(0xFFDBE5DA)
val surfaceVariantDark = Color(0xFF3C4A3E)
val onSurfaceVariantDark = Color(0xFFBACBBB)
val outlineDark = Color(0xFF859586)
val outlineVariantDark = Color(0xFF3C4A3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDBE5DA)
val inverseOnSurfaceDark = Color(0xFF2A332B)
val inversePrimaryDark = Color(0xFF006D3A)







